import { motion } from "framer-motion";
import { StickyNote, BookOpen, Calendar, Heart, RotateCcw, Download, ImageIcon, Loader2 } from "lucide-react";
import { useState, useEffect, useCallback } from "react";
import jsPDF from "jspdf";
import { saveGeneratedImage } from "@/lib/imageGallery";

/* ── Pastel color values for PDF ── */
const PDF_COLORS = {
  mint: { r: 166, g: 217, b: 200 },
  peach: { r: 245, g: 200, b: 175 },
  lavender: { r: 200, g: 180, b: 220 },
  sky: { r: 175, g: 210, b: 240 },
  rose: { r: 235, g: 185, b: 200 },
  lemon: { r: 240, g: 225, b: 170 },
};

/* ── PDF Export Helper ── */
function exportToPdf(
  title: string,
  accentColor: keyof typeof PDF_COLORS,
  buildContent: (doc: jsPDF, startY: number) => void
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const c = PDF_COLORS[accentColor];

  // Pastel header band
  doc.setFillColor(c.r, c.g, c.b);
  doc.rect(0, 0, 210, 38, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(50, 50, 50);
  doc.text(title, 20, 24);

  // Date subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" }), 20, 32);

  // Accent line
  doc.setDrawColor(c.r - 30, c.g - 30, c.b - 30);
  doc.setLineWidth(0.5);
  doc.line(20, 42, 190, 42);

  doc.setTextColor(40, 40, 40);
  buildContent(doc, 50);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by NexusAI ✨", 20, 287);

  doc.save(`${title.replace(/\s+/g, "_").toLowerCase()}.pdf`);
}

function PdfButton({ onClick }: { onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-lg bg-background/60 hover:bg-background text-muted-foreground hover:text-foreground transition-colors"
      title="Download as PDF"
    >
      <Download size={13} />
      <span>PDF</span>
    </button>
  );
}

/* ── Visual Note Card ── */
export function NoteCard({ title, items }: { title: string; items: string[] }) {
  const handlePdf = () => {
    exportToPdf(title, "lemon", (doc, y) => {
      doc.setFontSize(11);
      items.forEach((item, i) => {
        const currentY = y + i * 12;
        if (currentY > 270) return;
        // Bullet circle
        doc.setFillColor(PDF_COLORS.lemon.r, PDF_COLORS.lemon.g, PDF_COLORS.lemon.b);
        doc.circle(25, currentY - 1.5, 2, "F");
        doc.setFont("helvetica", "normal");
        doc.text(item, 32, currentY);
      });
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="tool-card tool-card-note my-3"
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <StickyNote size={18} className="text-lemon-foreground" />
          <h3 className="font-bold text-base">{title}</h3>
        </div>
        <PdfButton onClick={handlePdf} />
      </div>
      <ul className="space-y-2">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm">
            <span className="mt-1 w-2 h-2 rounded-full bg-lemon-foreground/40 flex-shrink-0" />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </motion.div>
  );
}

/* ── Flashcard ── */
export function FlashcardSet({ cards }: { cards: { front: string; back: string }[] }) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const card = cards[currentIndex];

  const handlePdf = () => {
    exportToPdf("Flashcards", "lavender", (doc, y) => {
      cards.forEach((c, i) => {
        const currentY = y + i * 22;
        if (currentY > 255) return;
        // Card background
        doc.setFillColor(PDF_COLORS.lavender.r, PDF_COLORS.lavender.g, PDF_COLORS.lavender.b);
        doc.roundedRect(20, currentY - 5, 170, 18, 3, 3, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.text(`Q: ${c.front}`, 25, currentY + 1);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.text(`A: ${c.back}`, 25, currentY + 8);
      });
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="tool-card tool-card-flashcard my-3"
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <BookOpen size={18} className="text-lavender-foreground" />
          <h3 className="font-bold text-base">Flashcards</h3>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">
            {currentIndex + 1} / {cards.length}
          </span>
          <PdfButton onClick={handlePdf} />
        </div>
      </div>

      <div
        onClick={() => setFlipped(!flipped)}
        className="cursor-pointer min-h-[120px] rounded-xl bg-background/60 p-5 flex items-center justify-center text-center transition-all hover:shadow-md"
      >
        <div>
          <p className="text-xs text-muted-foreground mb-1">
            {flipped ? "Answer" : "Question"} — tap to flip
          </p>
          <p className={`text-sm font-medium ${flipped ? "text-primary" : ""}`}>
            {flipped ? card.back : card.front}
          </p>
        </div>
      </div>

      <div className="flex items-center justify-between mt-3">
        <button
          onClick={() => { setFlipped(false); setCurrentIndex(Math.max(0, currentIndex - 1)); }}
          disabled={currentIndex === 0}
          className="text-xs px-3 py-1.5 rounded-lg bg-background/60 hover:bg-background disabled:opacity-30 transition-colors"
        >
          ← Prev
        </button>
        <button
          onClick={() => setFlipped(false)}
          className="p-1.5 rounded-lg bg-background/60 hover:bg-background transition-colors"
          title="Reset"
        >
          <RotateCcw size={14} />
        </button>
        <button
          onClick={() => { setFlipped(false); setCurrentIndex(Math.min(cards.length - 1, currentIndex + 1)); }}
          disabled={currentIndex === cards.length - 1}
          className="text-xs px-3 py-1.5 rounded-lg bg-background/60 hover:bg-background disabled:opacity-30 transition-colors"
        >
          Next →
        </button>
      </div>
    </motion.div>
  );
}

/* ── Daily Planner ── */
export function PlannerCard({ title, tasks }: { title: string; tasks: { time: string; task: string; done?: boolean }[] }) {
  const [checkedItems, setCheckedItems] = useState<Set<number>>(new Set());

  const toggle = (i: number) => {
    setCheckedItems((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });
  };

  const handlePdf = () => {
    exportToPdf(title, "mint", (doc, y) => {
      doc.setFontSize(10);
      tasks.forEach((item, i) => {
        const currentY = y + i * 12;
        if (currentY > 270) return;
        const checked = checkedItems.has(i);
        // Time badge
        doc.setFillColor(PDF_COLORS.mint.r, PDF_COLORS.mint.g, PDF_COLORS.mint.b);
        doc.roundedRect(20, currentY - 4, 22, 8, 2, 2, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.text(item.time, 22, currentY + 1);
        // Task text
        doc.setFont("helvetica", checked ? "italic" : "normal");
        doc.setFontSize(10);
        doc.setTextColor(checked ? 160 : 40, checked ? 160 : 40, checked ? 160 : 40);
        doc.text(`${checked ? "✓ " : "○ "}${item.task}`, 46, currentY + 1);
        doc.setTextColor(40, 40, 40);
      });
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="tool-card tool-card-planner my-3"
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Calendar size={18} className="text-mint-foreground" />
          <h3 className="font-bold text-base">{title}</h3>
        </div>
        <PdfButton onClick={handlePdf} />
      </div>
      <div className="space-y-2">
        {tasks.map((item, i) => (
          <div
            key={i}
            onClick={() => toggle(i)}
            className={`flex items-center gap-3 p-2.5 rounded-xl bg-background/60 cursor-pointer transition-all hover:bg-background/80 ${
              checkedItems.has(i) ? "opacity-50" : ""
            }`}
          >
            <div
              className={`w-5 h-5 rounded-full border-2 flex items-center justify-center flex-shrink-0 transition-colors ${
                checkedItems.has(i) ? "bg-primary border-primary" : "border-muted-foreground/30"
              }`}
            >
              {checkedItems.has(i) && (
                <span className="text-primary-foreground text-xs">✓</span>
              )}
            </div>
            <span className="text-xs font-mono text-muted-foreground w-14 flex-shrink-0">
              {item.time}
            </span>
            <span className={`text-sm flex-1 ${checkedItems.has(i) ? "line-through" : ""}`}>
              {item.task}
            </span>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

/* ── Mood Board ── */
export function MoodBoard({ title, items }: { title: string; items: { text: string; color: string }[] }) {
  const colorMap: Record<string, string> = {
    peach: "bg-peach/60 text-peach-foreground",
    mint: "bg-mint/60 text-mint-foreground",
    lavender: "bg-lavender/60 text-lavender-foreground",
    sky: "bg-sky/60 text-sky-foreground",
    rose: "bg-rose/60 text-rose-foreground",
    lemon: "bg-lemon/60 text-lemon-foreground",
  };

  const handlePdf = () => {
    exportToPdf(title, "rose", (doc, y) => {
      const cols = 2;
      const cellW = 80;
      const cellH = 25;
      const gap = 10;
      items.forEach((item, i) => {
        const col = i % cols;
        const row = Math.floor(i / cols);
        const x = 20 + col * (cellW + gap);
        const currentY = y + row * (cellH + gap);
        if (currentY > 260) return;
        const c = PDF_COLORS[item.color as keyof typeof PDF_COLORS] || PDF_COLORS.lavender;
        doc.setFillColor(c.r, c.g, c.b);
        doc.roundedRect(x, currentY, cellW, cellH, 4, 4, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);
        doc.text(item.text, x + cellW / 2, currentY + cellH / 2 + 2, { align: "center" });
      });
      doc.setTextColor(40, 40, 40);
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="tool-card tool-card-moodboard my-3"
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Heart size={18} className="text-rose-foreground" />
          <h3 className="font-bold text-base">{title}</h3>
        </div>
        <PdfButton onClick={handlePdf} />
      </div>
      <div className="grid grid-cols-2 gap-2">
        {items.map((item, i) => (
          <div
            key={i}
            className={`p-4 rounded-xl ${colorMap[item.color] || colorMap.lavender} font-handwritten text-lg text-center`}
          >
            {item.text}
          </div>
        ))}
      </div>
    </motion.div>
  );
}

/* ── AI Image Card ── */
export function ImageCard({ prompt, caption }: { prompt: string; caption?: string }) {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const generateImage = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const resp = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-image`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
          },
          body: JSON.stringify({ prompt }),
        }
      );
      if (!resp.ok) {
        const data = await resp.json().catch(() => ({ error: "Failed" }));
        throw new Error(data.error || "Image generation failed");
      }
      const data = await resp.json();
      if (data.imageUrl) {
        setImageUrl(data.imageUrl);
        // Save to gallery
        saveGeneratedImage({ prompt, caption, imageUrl: data.imageUrl });
      } else {
        throw new Error("No image returned");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to generate image");
    } finally {
      setLoading(false);
    }
  }, [prompt, caption]);

  useEffect(() => {
    generateImage();
  }, [generateImage]);

  const handleDownload = () => {
    if (!imageUrl) return;
    const link = document.createElement("a");
    link.href = imageUrl;
    link.download = `${(caption || prompt).slice(0, 30).replace(/\s+/g, "_")}.png`;
    link.click();
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="tool-card my-3"
      style={{
        background: "linear-gradient(135deg, hsl(200 60% 85% / 0.5), hsl(270 45% 87% / 0.3))",
        borderColor: "hsl(200 60% 85% / 0.5)",
      }}
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <ImageIcon size={18} className="text-sky-foreground" />
          <h3 className="font-bold text-base">Generated Image</h3>
        </div>
        {imageUrl && (
          <button
            onClick={handleDownload}
            className="flex items-center gap-1 text-xs px-2.5 py-1.5 rounded-lg bg-background/60 hover:bg-background text-muted-foreground hover:text-foreground transition-colors"
          >
            <Download size={13} />
            <span>Save</span>
          </button>
        )}
      </div>

      <div className="rounded-xl overflow-hidden bg-background/40 min-h-[200px] flex items-center justify-center">
        {loading && (
          <div className="flex flex-col items-center gap-3 py-8 text-muted-foreground">
            <Loader2 size={28} className="animate-spin text-primary" />
            <p className="text-sm">Generating image…</p>
            <p className="text-xs max-w-[300px] text-center opacity-60">{prompt}</p>
          </div>
        )}
        {error && (
          <div className="flex flex-col items-center gap-2 py-8 text-muted-foreground">
            <p className="text-sm">😔 {error}</p>
            <button
              onClick={generateImage}
              className="text-xs px-3 py-1.5 rounded-lg bg-primary text-primary-foreground hover:opacity-90 transition-opacity"
            >
              Try Again
            </button>
          </div>
        )}
        {imageUrl && !loading && (
          <img
            src={imageUrl}
            alt={caption || prompt}
            className="w-full rounded-xl"
          />
        )}
      </div>

      {caption && !loading && (
        <p className="text-sm text-muted-foreground mt-2 text-center italic">{caption}</p>
      )}
    </motion.div>
  );
}
